package idbase

object Names {
  val titre = "Titre"
  val reference = "Référence"
  val url = "URL"
  val annee = "Année"
  val notion = "Notions"
  val niveau = "Niveaux"
  val methodePedagogique = "Méthodes pédagogiques"
  val disciplineInfodoc = "Discipline Information-documentation"
  val interdisciplinarite = "Interdisciplinarité"
  val dispositifPedagogique = "Dispositif pédagogique"
  val dispositifEducatif = "Dispositif éducatif"
  val auteur = "Auteur"
  val source = "Source"
  val production = "Production"
  val scenario = "Scénario"
  val objectifT1 = "Objectif(s) T1"
  val objectifT2 = "Objectif(s) T2"
  val objectifT3 = "Objectif(s) T3"
  val demarche = "Démarche"
  val deroulement = "Déroulement"
  val tache = "Tâche"
  val materiau = "Matériau(x)"
  val evaluation = "Évaluation"
  val outilDidactique = "Outil(s) didactique(s)"
  val duree = "Durée"
  val commentaire = "Commentaire"
}
