package idbase

object Names {
  val titre = "Titre"
  val reference = "Référence"
  val url = "URL"
  val annee = "Année"
  val notion = "Notion(s)"
  val niveau = "Niveau(x)"
  val methodePedagogique = "Méthode pédagogique"
  val interdisciplinarite = "Interdisciplinarité"
  val dispositifPedagogique = "Dispositif pédagogique"
  val dispositifEducatif = "Dispositif éducatif"
  val source = "Source"
  val production = "Production"
  val scenario = "Scénario"
  val objectifT1 = "Savoirs pratiques (ex T1)"
  val objectifT2 = "Savoirs théoriques (ex T2)"
  val objectifT3 = "Savoirs éthiques (ex T3)"
  val demarche = "Démarche"
  val deroulement = "Déroulement"
  val tache = "Tâche"
  val materiau = "Matériau(x)"
  val evaluation = "Évaluation"
  val outilEvaluation = "Outils d'évaluation"
  val outilDidactique = "Outil(s) didactique(s)"
  val ficheEleve = "Fiche(s) élève(s)"
  val duree = "Durée"
  val commentaire = "Commentaire"
}
